AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambda go send to slack.
Resources:
  SendSlack:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: "main.zip"
      # CloudWatch Event設定
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: cron(* * * * ? *)
      #環境変数
        Environment:
          Variables:
            slackURL: https://hooks.slack.com/services/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
